# Generated by Django 4.0.2 on 2022-02-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100000)),
                ('code', models.CharField(max_length=10000000000)),
                ('date', models.DateField()),
            ],
        ),
    ]
